name: GPU Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - codebuild-gpu-test2-${{ github.run_id }}-${{ github.run_attempt }}
      - image:381492037974.dkr.ecr.us-east-1.amazonaws.com/codebuild-cuda12-test:latest
      - instance-size:gpu_large

    steps:
      - uses: actions/checkout@v3
      
      - name: Create and Run CUDA Test
        run: |
          echo "=== Creating CUDA Test ==="
          cat > test.cu << 'EOL'
          #include <stdio.h>
          
          __global__ void hello_kernel() {
              printf("Hello from GPU! (Thread %d)\n", threadIdx.x);
          }
          
          int main() {
              hello_kernel<<<1, 4>>>();
              cudaDeviceSynchronize();
              return 0;
          }
          EOL
